-- Eliminar la tabla LIBROS si existe
DROP TABLE LIBRO;

-- Eliminar la secuencia LIBROS_SEQ si existe
DROP SEQUENCE LIBRO_SEQ;

-- Crear la secuencia para generar IDs automáticos
CREATE SEQUENCE LIBRO_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Crear la tabla LIBROS
CREATE TABLE LIBRO (
    ID NUMBER DEFAULT LIBRO_SEQ.NEXTVAL PRIMARY KEY,
    TITULO VARCHAR2(255) NOT NULL,
    AUTOR VARCHAR2(255),
    FECHA_PUBLICACION DATE,
    DISPONIBLE CHAR(1) DEFAULT 'Y' NOT NULL
);

-- Insertar algunos datos
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', TO_DATE('1997-06-26', 'YYYY-MM-DD'), 'Y');
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('El Señor de los Anillos', 'J.R.R. Tolkien', TO_DATE('1954-07-29', 'YYYY-MM-DD'), 'Y');
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('Dune', 'Frank Herbert', TO_DATE('1965-08-01', 'YYYY-MM-DD'), 'N');
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('1984', 'George Orwell', TO_DATE('1949-06-08', 'YYYY-MM-DD'), 'Y');
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('Matar a un ruiseñor', 'Harper Lee', TO_DATE('1960-07-11', 'YYYY-MM-DD'), 'Y');
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('Cien años de soledad', 'Gabriel García Márquez', TO_DATE('1967-05-30', 'YYYY-MM-DD'), 'Y');
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('El Gran Gatsby', 'F. Scott Fitzgerald', TO_DATE('1925-04-10', 'YYYY-MM-DD'), 'Y');
INSERT INTO LIBRO (TITULO, AUTOR, FECHA_PUBLICACION, DISPONIBLE) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', TO_DATE('1605-01-16', 'YYYY-MM-DD'), 'Y');


